--USE CTAS TO CREATE TABLE BASED ON NO.OF ISSUE OF EACH BOOKS
IF OBJECT_ID('dbo.ISSUEDTIMESOFBOOK', 'U') IS NOT NULL
	DROP TABLE dbo.ISSUEDTIMESOFBOOK
GO
SELECT 
COUNT(BOOKS.isbn) AS NO_OF_ISSUED,
BOOKS.BOOK_TITLE
INTO ISSUEDTIMESOFBOOK
FROM BOOKS
LEFT JOIN issued_date
ON BOOKS.isbn= issued_date.issued_book_isbn
GROUP BY BOOKS.isbn, BOOKS.book_title
