--DETAILS OF BOOKS IN EACH CATEGORY USING WINDOW FUNCTION
SELECT 
B.ISBN,
B.BOOK_TITLE,
B.CATEGORY,
B.RENTAL_PRICE,
B.AUTHOR,
COUNT(*) OVER(PARTITION BY CATEGORY) AS TOTALBOOKSINEACHCATEGORY
FROM BOOKS B